name: Deploy Function and Web App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_NAME: demo-multimodal-rag
      AZURE_FUNCTIONAPP_NAME: chatbot-multimodal
      AZURE_RESOURCE_GROUP: demoabm

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        curl -Ls https://astral.sh/uv/install.sh | bash
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install project dependencies and export requirements.txt
      run: |
        uv venv
        source .venv/bin/activate
        uv pip compile pyproject.toml > requirements.txt
        uv sync

    - name: Copy requirements.txt to app and azure_function
      run: |
        cp requirements.txt app/
        cp requirements.txt azure_function/

    # --- Install dependencies for Azure Function App ---
    - name: Install Azure Function dependencies
      run: |
        cd azure_function
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        cd ..

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './azure_function'

    - name: Deploy Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: './app'
        slot-name: 'production'