name: Deploy Function and Web App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_NAME: demo-multimodal-rag
      AZURE_FUNCTIONAPP_NAME: chatbot-multimodal
      AZURE_RESOURCE_GROUP: demoabm

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Ensure requirements.txt is present in both deployment folders
    - name: Copy requirements.txt to app and azure_function
      run: |
        cp requirements.txt app/
        cp requirements.txt azure_function/

    # Azure Login (required for deployment)
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy Azure Function (Oryx will build from requirements.txt in azure_function/)
    - name: Deploy Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './azure_function'

    # Deploy App Service (Oryx will build from requirements.txt in app/)
    - name: Deploy Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: './app'
        slot-name: 'production'