name: Deploy Function and Web App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_NAME: demo-multimodal-rag
      AZURE_FUNCTIONAPP_NAME: chatbot-multimodal
      AZURE_RESOURCE_GROUP: demoabm

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        curl -Ls https://astral.sh/uv/install.sh | bash
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install project dependencies with uv
      run: |
        uv venv
        source .venv/bin/activate
        uv sync

    # Azure Login (required for deployment)
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy Azure Function
    - name: Deploy Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './azure_function'

    # Deploy App Service
    - name: Deploy Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: './app'
        slot-name: 'production'